
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int P_C = 39;
  public static final int P_A = 38;
  public static final int MULTI_COMMENT = 47;
  public static final int MULT = 29;
  public static final int CONST = 22;
  public static final int T_POINTS = 37;
  public static final int CASE = 15;
  public static final int DOUBLE = 10;
  public static final int GREATER = 32;
  public static final int CONTINUE = 3;
  public static final int INT = 11;
  public static final int OUT = 7;
  public static final int LESS = 28;
  public static final int FOR = 24;
  public static final int STATIC = 19;
  public static final int IDENTIFICADOR = 44;
  public static final int CARACTER = 51;
  public static final int BOOL = 21;
  public static final int DIV = 30;
  public static final int DIGIT = 45;
  public static final int PLUS = 27;
  public static final int QUOTE = 42;
  public static final int MIN = 31;
  public static final int IF = 18;
  public static final int DECIMAL = 49;
  public static final int EOF = 0;
  public static final int RETURN = 8;
  public static final int EQUAL = 33;
  public static final int TRUE = 9;
  public static final int NEW = 6;
  public static final int error = 1;
  public static final int COMA = 34;
  public static final int CADENA = 52;
  public static final int SEMI_COLON = 35;
  public static final int NULL = 12;
  public static final int BREAK = 2;
  public static final int VOID = 20;
  public static final int ERROR = 48;
  public static final int SWITCH = 14;
  public static final int S_QUOTE = 43;
  public static final int LL_C = 41;
  public static final int FOREACH = 5;
  public static final int LL_A = 40;
  public static final int ELSE = 17;
  public static final int POINT = 36;
  public static final int WHILE = 26;
  public static final int DEFAULT = 16;
  public static final int PUBLIC = 13;
  public static final int BOOLEANO = 50;
  public static final int STRING = 25;
  public static final int SIMPLE_COMMENT = 46;
  public static final int FALSE = 23;
  public static final int PRINT = 53;
  public static final int DO = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BREAK",
  "CONTINUE",
  "DO",
  "FOREACH",
  "NEW",
  "OUT",
  "RETURN",
  "TRUE",
  "DOUBLE",
  "INT",
  "NULL",
  "PUBLIC",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "ELSE",
  "IF",
  "STATIC",
  "VOID",
  "BOOL",
  "CONST",
  "FALSE",
  "FOR",
  "STRING",
  "WHILE",
  "PLUS",
  "LESS",
  "MULT",
  "DIV",
  "MIN",
  "GREATER",
  "EQUAL",
  "COMA",
  "SEMI_COLON",
  "POINT",
  "T_POINTS",
  "P_A",
  "P_C",
  "LL_A",
  "LL_C",
  "QUOTE",
  "S_QUOTE",
  "IDENTIFICADOR",
  "DIGIT",
  "SIMPLE_COMMENT",
  "MULTI_COMMENT",
  "ERROR",
  "DECIMAL",
  "BOOLEANO",
  "CARACTER",
  "CADENA",
  "PRINT"
  };
}

